// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYGIMEPbxSsHuKAxIhPPH4K7m2lTVR6e4',
    appId: '1:658889363766:web:589324b76958824b6aa397',
    messagingSenderId: '658889363766',
    projectId: 'rfid-attend',
    authDomain: 'rfid-attend.firebaseapp.com',
    databaseURL: 'https://rfid-attend-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-attend.firebasestorage.app',
    measurementId: 'G-T3WZ7HDKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5MppH7_0iXsrDqe21jPbhDpgAz_r_b-M',
    appId: '1:658889363766:android:3c079cd3e9431afb6aa397',
    messagingSenderId: '658889363766',
    projectId: 'rfid-attend',
    databaseURL: 'https://rfid-attend-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-attend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXTjYipaaeoU1AaXygViZw_mtxjOx0R_w',
    appId: '1:658889363766:ios:307c41248367c4b16aa397',
    messagingSenderId: '658889363766',
    projectId: 'rfid-attend',
    databaseURL: 'https://rfid-attend-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-attend.firebasestorage.app',
    iosBundleId: 'com.example.iotproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXTjYipaaeoU1AaXygViZw_mtxjOx0R_w',
    appId: '1:658889363766:ios:307c41248367c4b16aa397',
    messagingSenderId: '658889363766',
    projectId: 'rfid-attend',
    databaseURL: 'https://rfid-attend-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-attend.firebasestorage.app',
    iosBundleId: 'com.example.iotproject',
  );
}
